import {
  ClipboardList,
  CheckCircle,
  AlertTriangle,
  Box,
  Banknote,
  Settings,
  Pencil,
  X,
  Circle,
  SquareStack,
  Star,
  ArrowUp,
  ArrowDown,
  Gem,
  Plus,
  Flag,
  Sparkles,
  User,
  Power,
  AlertCircle,
  Smile,
  Wave,
  Calendar,
  Search,
  Factory,
  FlaskConical,
  Cookie,
  Truck,
  BarChart2,
  PlusCircle,
  MinusCircle,
  ChevronDown,
  ChevronRight,
  MoreHorizontal,
  Edit3,
  Trash2,
  PlusSquare,
  CheckSquare,
  Clock,
  FileText,
  Activity,
  Home,
  FolderOpen,
  Archive,
  RefreshCw,
  Save,
  Upload,
  Download,
  Filter,
  SlidersHorizontal,
  AlertOctagon,
  Shield,
  Users,
  FileCheck,
  BarChart,
  PieChart,
  TrendingUp,
  DollarSign,
  Scale,
  PackageCheck,
  TruckDelivery,
  ClipboardCheck,
  ClipboardX,
  ClipboardType,
  ClipboardEdit,
  ListChecks,
  CheckCircle2,
  XCircle,
  Info,
  HelpCircle,
  MessageSquare,
  Phone,
  Mail,
  MapPin,
  Globe,
  Sun,
  Moon,
  Cloud,
  Droplets,
  Thermometer,
  Wind,
  Zap,
  Wifi,
  WifiOff,
  Camera,
  Image,
  Video,
  Music,
  Mic,
  Headphones,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Keyboard,
  Mouse,
  Printer,
  HardDrive,
  Database,
  Server,
  CloudUpload,
  CloudDownload,
  Link,
  Unlink,
  Copy,
  Scissors,
  Paintbrush,
  Type,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  List,
  ListOrdered,
  Grid3X3,
  Grid4X4,
  Divide,
  Quote,
  Code,
  Terminal,
  Play,
  Pause,
  Stop,
  SkipForward,
  SkipBack,
  FastForward,
  Rewind,
  Volume2,
  VolumeX,
  Maximize2,
  Minimize2,
  Fullscreen,
  CornerDownLeft,
  Send,
  Paperclip,
  Link2,
  Unlock,
  Lock,
  Eye,
  EyeOff,
  Edit,
  Trash,
  CopyCheck,
  RotateCw,
  RotateCcw,
  FlipHorizontal,
  FlipVertical,
  Move,
  MoveVertical,
  MoveHorizontal,
  Crop,
  Sliders,
  ZoomIn,
  ZoomOut,
  Search as SearchIcon,
  Filter as FilterIcon,
  Bell,
  BellOff,
  Calendar as CalendarIcon,
  Clock as ClockIcon,
  History,
  Bookmark,
  BookmarkPlus,
  BookmarkMinus,
  Tag,
  Hash,
  AtSign,
  Percent,
  DollarSign as DollarSignIcon,
  Euro,
  Pound,
  Bitcoin,
  CreditCard,
  Wallet,
  ShoppingCart,
  ShoppingBag,
  Package,
  Box as BoxIcon,
  Layers,
  Stack,
  Archive as ArchiveIcon,
  Folder,
  FolderOpen,
  FolderPlus,
  FolderMinus,
  File,
  FilePlus,
  FileMinus,
  FileEdit,
  FileX,
  FileCheck as FileCheckIcon,
  FileText as FileTextIcon,
  FileImage,
  FileVideo,
  FileAudio,
  FileArchive,
  FileCode,
  FileSpreadsheet,
  FileJson,
  FileType,
  FileBadge2,
  FileBadge,
  FileHeart,
  FileLock,
  FileUnlock,
  FileSearch,
  FileQuestion,
  FileAlert,
  FileWarning,
  FileInfo,
  FileX2,
  FileCheck2,
  FileClock,
  FileDiff,
  FileSymlink,
  FileCog,
  FileUp,
  FileDown,
  FileOutput,
  FileInput,
  FilePlus2,
  FileMinus2,
  FileEdit2,
  FileX2 as FileX2Icon,
  FileCheck2 as FileCheck2Icon,
  FileClock as FileClockIcon,
  FileDiff as FileDiffIcon,
  FileSymlink as FileSymlinkIcon,
  FileCog as FileCogIcon,
  FileUp as FileUpIcon,
  FileDown as FileDownIcon,
  FileOutput as FileOutputIcon,
  FileInput as FileInputIcon,
  GripVertical,
  GripHorizontal,
  Rows3,
  Rows4,
  Columns,
  Rows,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  Split,
  Merge,
  MoreVertical,
  MoreHorizontal as MoreHorizontalIcon,
  ChevronUp,
  ChevronDown as ChevronDownIcon,
  ChevronLeft,
  ChevronRight as ChevronRightIcon,
  ChevronsUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  Play as PlayIcon,
  Pause as PauseIcon,
  Square,
  Triangle,
  Circle as CircleIcon,
  Diamond,
  Hexagon,
  Octagon,
  Pentagon,
  Star as StarIcon,
  Heart,
  Flag as FlagIcon,
  TrendingUp as TrendingUpIcon,
  TrendingDown,
  Activity as ActivityIcon,
  AlertCircle as AlertCircleIcon,
  AlertTriangle as AlertTriangleIcon,
  AlertOctagon as AlertOctagonIcon,
  HelpCircle as HelpCircleIcon,
  Info as InfoIcon,
  XCircle as XCircleIcon,
  CheckCircle as CheckCircleIcon,
  CheckCircle2 as CheckCircle2Icon,
  Check,
  X as XIcon,
  Plus as PlusIcon,
  Minus,
  Divide as DivideIcon,
  Percent as PercentIcon,
  RefreshCw as RefreshCwIcon,
  RotateCw as RotateCwIcon,
  RotateCcw,
  Undo,
  Redo,
  Undo2,
  Redo2,
  History as HistoryIcon,
  Save as SaveIcon,
  Upload as UploadIcon,
  Download as DownloadIcon,
  Share,
  Share2,
  Share2 as Share2Icon,
  Link as LinkIcon,
  Unlink as UnlinkIcon,
  Copy as CopyIcon,
  Scissors as ScissorsIcon,
  Paintbrush as PaintbrushIcon,
  Type as TypeIcon,
  Bold as BoldIcon,
  Italic as ItalicIcon,
  Underline as UnderlineIcon,
  Strikethrough as StrikethroughIcon,
  AlignLeft as AlignLeftIcon,
  AlignCenter as AlignCenterIcon,
  AlignRight as AlignRightIcon,
  AlignJustify as AlignJustifyIcon,
  List as ListIcon,
  ListOrdered as ListOrderedIcon,
  Grid3X3 as Grid3X3Icon,
  Grid4X4 as Grid4X4Icon,
  Columns as ColumnsIcon,
  PanelLeft as PanelLeftIcon,
  PanelRight as PanelRightIcon,
  PanelTop as PanelTopIcon,
  PanelBottom as PanelBottomIcon,
  Split as SplitIcon,
  Merge as MergeIcon,
  ChevronsUp as ChevronsUpIcon,
  ChevronsDown as ChevronsDownIcon,
  ChevronsLeft as ChevronsLeftIcon,
  ChevronsRight as ChevronsRightIcon,
  Mic as MicIcon,
  Video as VideoIcon,
  Image as ImageIcon,
  Music as MusicIcon,
  Headphones as HeadphonesIcon,
  Maximize2 as Maximize2Icon,
  Minimize2 as Minimize2Icon,
  Fullscreen as FullscreenIcon,
  CornerDownLeft as CornerDownLeftIcon,
  Send as SendIcon,
  Paperclip as PaperclipIcon,
  Link2 as Link2Icon,
  Unlock as UnlockIcon,
  Lock as LockIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  Edit as EditIcon,
  Trash as TrashIcon,
  CopyCheck as CopyCheckIcon,
  Crop as CropIcon,
  Sliders as SlidersIcon,
  ZoomIn as ZoomInIcon,
  ZoomOut as ZoomOutIcon,
  Search as SearchIcon2,
  Filter as FilterIcon2,
  Bell as BellIcon,
  BellOff as BellOffIcon,
  Calendar as CalendarIcon2,
  Clock as ClockIcon2,
  Bookmark as BookmarkIcon,
  Tag as TagIcon,
  Hash as HashIcon,
  AtSign as AtSignIcon,
  DollarSign as DollarSignIcon2,
  Euro as EuroIcon,
  Bitcoin as BitcoinIcon,
  CreditCard as CreditCardIcon,
  ShoppingCart as ShoppingCartIcon,
  ShoppingBag as ShoppingBagIcon,
  Package as PackageIcon,
  Box as BoxIcon2,
  Layers as LayersIcon,
  Stack as StackIcon,
  Home as HomeIcon,
  Settings as SettingsIcon,
  User as UserIcon,
  Users as UsersIcon,
  FileText as FileTextIcon2,
  BarChart as BarChartIcon,
  PieChart as PieChartIcon,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  // Dashboard & stats
  '📋': ClipboardList,
  '✅': CheckCircle,
  '⚠️': AlertTriangle,
  '🚨': AlertCircle,
  '😀': Smile,
  '👋': Wave,

  // Navigation/entities
  '📦': Package,
  '💰': Banknote,
  '📊': BarChart2,
  '📅': Calendar,
  '🔍': Search,
  '🏭': Factory,
  '🫙': FlaskConical,
  '🥐': Cookie,
  '🚚': Truck,

  // Actions
  '⚙': Settings,
  '✎': Pencil,
  '✕': X,
  '⊕': Plus,
  '⏻': Power,

  // Layout icons
  '◎': Circle,
  '▦': SquareStack,
  '✦': Star,
  '▲': ArrowUp,
  '↓': ArrowDown,
  '◈': Gem,
  '⚑': Flag,
  '◉': Circle,
  '✧': Sparkles,
  '👤': User,

  // Additional UI icons from pages
  '📄': FileText,
  '🗑️': Trash2,
  '📤': Upload,
  '📥': Download,
  '✏️': Edit3,
  '↻': RefreshCw,
  '💾': Save,
  '🎯': Target,
  '🏷️': Tag,
  '📈': TrendingUp,
  '📉': TrendingDown,
  '⚖️': Scale,
  '🔒': Lock,
  '🔓': Unlock,
  '👁️': Eye,
  '👁️‍🗨️': EyeOff,
  '📝': Edit,
  '✓': CheckSquare,
  '☐': Square,
  '–': MinusCircle,
  '⋯': MoreHorizontal,
  '▼': ChevronDown,
  '▶': Play,
  '⏸': Pause,
  '⏹': Square,
}

interface IconProps {
  name: string
  size?: number
  className?: string
  style?: React.CSSProperties
}

export function Icon({ name, size = 18, className, style }: IconProps) {
  const IconComponent = iconMap[name]

  if (!IconComponent) {
    // If icon not found, render the emoji as fallback
    return <span className={className} style={style}>{name}</span>
  }

  return (
    <IconComponent
      size={size}
      className={className}
      style={style}
      strokeWidth={1.5}
    />
  )
}

// Export individual icons for direct use
export {
  ClipboardList,
  CheckCircle,
  AlertTriangle,
  AlertCircle,
  Smile,
  Wave,
  Package,
  BoxIcon,
  Settings,
  Pencil,
  X,
  Plus,
  Power,
  Circle,
  SquareStack,
  Star,
  ArrowUp,
  ArrowDown,
  Gem,
  Flag,
  Sparkles,
  User,
  BarChart2,
  Calendar,
  Search,
  Factory,
  FlaskConical,
  Cookie,
  Truck,
  ClipboardCheck,
  ClipboardX,
  ClipboardType,
  ClipboardEdit,
  ListChecks,
  CheckCircle2,
  XCircle,
  Info,
  HelpCircle,
  MessageSquare,
  Phone,
  Mail,
  MapPin,
  Globe,
  Home as HomeIcon,
  FolderOpen,
  Archive,
  RefreshCw,
  Save,
  Upload,
  Download,
  Filter,
  SlidersHorizontal,
  Shield,
  Users,
  FileCheck,
  BarChart,
  PieChart,
  TrendingUp,
  DollarSign,
  Scale,
  PackageCheck,
  TruckDelivery,
  ClipboardCheck as ClipboardCheckIcon,
  ClipboardX as ClipboardXIcon,
  Trash2,
  Edit3,
  MoreHorizontal as MoreHorizontalIcon,
  ChevronDown as ChevronDownIcon,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  Play,
  Pause,
  Square,
  CircleIcon,
  Target,
  Tag,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Edit,
  Copy,
  Crop,
  Sliders,
  ZoomIn,
  ZoomOut,
  Bell,
  Clock,
  Bookmark,
  Hash,
  AtSign,
  Bitcoin,
  CreditCard,
  ShoppingCart,
  ShoppingBag,
  Layers,
  Stack,
  FileText,
  FileImage,
  FileVideo,
  FileAudio,
  FileArchive,
  FileCode,
  FileSpreadsheet,
  FileJson,
  FileType,
  FileBadge2,
  FileBadge,
  FileHeart,
  FileLock,
  FileUnlock,
  FileSearch,
  FileQuestion,
  FileAlert,
  FileWarning,
  FileInfo,
  Undo,
  Redo,
  Undo2,
  Redo2,
  History as HistoryIcon,
  Share,
  Share2,
  CopyCheck,
  RotateCw,
  RotateCcw,
  FlipHorizontal,
  FlipVertical,
  Move,
  MoveVertical,
  MoveHorizontal,
  GripVertical,
  GripHorizontal,
  Rows3,
  Rows4,
  Columns,
  Rows,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  Split,
  Merge,
  Minus,
  Divide,
  PlusSquare,
  MinusSquare,
  MinusCircle as MinusCircleIcon,
  PlusCircle,
  Arc,
  ArrowBigDown,
  ArrowBigLeft,
  ArrowBigRight,
  ArrowBigUp,
  ArrowDownCircle,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeftCircle,
  ArrowLeftRight,
  ArrowRightCircle,
  ArrowUpCircle,
  ArrowUpLeft,
  ArrowUpRight,
  Auge,
  Braces,
  Bug,
  Building,
  Building2,
  Cake,
  Car,
  CarFront,
  Castle,
  CheckCheck,
  ChevronFirst,
  ChevronLast,
  CircleDashed,
  Code2,
  Codepen,
  Command,
  Compass,
  Contact,
  Contrast,
  Cp,
  CreditCard as CreditCard2,
  Croissant,
  Crown,
  Dumbbell,
  Egg,
  Equal,
  Eraser,
  Euro as EuroIcon2,
  Flame,
  FolderTree,
  Footprints,
  Framer,
  Fuel,
  Gamepad2,
  Gift,
  Gift as GiftIcon,
  GitBranch,
  GitCommit,
  GitCompare,
  GitFork,
  GitMerge,
  GitPullRequest,
  Github,
  Gitlab,
  Globe2,
  Golf,
  GraduationCap,
  Hammer,
  HardHat,
  HardDrive as HardDrive2,
  Heart as HeartIcon,
  HelpCircle as HelpCircle2,
  Home,
  Hourglass,
  IceCream,
  ImagePlus,
  ImageMinus,
  ImageOff,
  Inbox,
  IndianRupee,
  Infinity,
  Info as Info2,
  Italic as Italic2,
  Key,
  Lampe,
  Landmark,
  Languages,
  Laptop2,
  Layers2,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  LayoutTemplate,
  Library,
  LifeBuoy,
  Lightbulb,
  Link as Link3,
  Link2 as Link23,
  ListMinus,
  ListPlus,
  ListTodo,
  ListX,
  Loader,
  Loader2,
  Locate,
  LocateFixed,
  Lock as Lock2,
  LogIn,
  LogOut,
  Mail as Mail2,
  Map,
  MapPinned,
  Maximize,
  Medal,
  Menu,
  MessageCircle,
  MessageSquare as MessageSquare2,
  Mic as Mic2,
  Minimize,
  MinusCircle,
  MinusSquare,
  Monitor as Monitor2,
  Moon,
  MoreVertical,
  MousePointer,
  MousePointer2,
  MousePointerClick,
  Move3D,
  MoveDiagonal,
  MoveDiagonal2,
  MoveHorizontal as MoveHorizontal2,
  MoveVertical as MoveVertical2,
  Music as Music2,
  Navigation,
  Network,
  Octagon,
  Orbits,
  Package as Package2,
  PackageCheck as PackageCheck2,
  PackageOpen,
  PackageX,
  PaintBucket,
  Palette,
  PartyPopper,
  PauseCircle,
  PenTool,
  PencilLine,
  Percent as Percent2,
  PersonStanding,
  Phone as Phone2,
  PhoneCall,
  PhoneIncoming,
  PhoneOff,
  PhoneOutgoing,
  PieChart as PieChart2,
  PiggyBank,
  Pin,
  PinOff,
  PlayCircle,
  Plug,
  PlusCircle as PlusCircleIcon,
  PlusSquare as PlusSquare2,
  Pocket,
  Pound as PoundIcon,
  Power as Power2,
  Printer as Printer2,
  Radio,
  Radio as RadioIcon,
  Receipt,
  ReceiptText,
  Recycle,
  Redo2 as Redo2Icon,
  RefreshCw as RefreshCw2,
  Refrigerator,
  Reply,
  ReplyAll,
  Rewind as Rewind2,
  RotateCcw as RotateCcw2,
  RotateCw as RotateCw2,
  Rss,
  Ruler,
  RussianRuble,
  Save as Save2,
  Scan,
  ScanBarcode,
  ScanLine,
  School,
  Scissors as Scissors2,
  ScreenShare,
  Search as Search3,
  SearchCheck,
  SearchSlash,
  Send as Send2,
  SeparatorHorizontal,
  SeparatorVertical,
  Settings as Settings2,
  Share as Share3,
  Share2 as Share22,
  Shield as Shield2,
  ShieldAlert,
  ShieldCheck,
  ShieldQuestion,
  ShoppingBag as ShoppingBag2,
  ShoppingCart as ShoppingCart2,
  Shuffle,
  Sidebar,
  SidebarClose,
  SidebarOpen,
  Sigma,
  SkipBack as SkipBack2,
  SkipForward as SkipForward2,
  Slack,
  Sliders as Sliders2,
  Smartphone as Smartphone2,
  Snowflake,
  Sofa,
  SortAsc,
  SortDesc,
  Soup,
  Space,
  SprayCan,
  Sprout,
  SquareStack as SquareStack2,
  Stack as Stack2,
  Star as Star2,
  StepBack,
  StepForward,
  Stethoscope,
  Sticker,
  StickyNote,
  StopCircle,
  Store,
  Sun as Sun2,
  Sunrise,
  Sunset,
  Sunrise as SunriseIcon,
  Sunset as SunsetIcon,
  SwapHorizontal,
  SwapHorizontal as SwapHorizontalIcon,
  SwapVertical,
  SwatchBook,
  Sword,
  Syringe,
  Table,
  Table2,
  Tablet as Tablet2,
  Tag as Tag2,
  Target,
  Telescope,
  Television,
  Television2,
  Terminal as Terminal2,
  Thermometer as Thermometer2,
  ThermometerSnowflake,
  ThermometerSun,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  TicketCheck,
  TicketMinus,
  TicketPercent,
  TicketX,
  Timer,
  TimerOff,
  TimerReset,
  ToggleLeft,
  ToggleRight,
  Tool,
  Torus,
  TrainLine,
  Tram,
  Trash as Trash2Icon,
  Trash2 as Trash22,
  Triangle,
  Trophy,
  Truck as Truck2,
  TruckDelivery as TruckDelivery2,
  Tuning,
  Tv,
  Tv2,
  Twitch,
  Twitter,
  Type as Type2,
  Umbrella,
  Underline as Underline2,
  Undo as Undo2Icon,
  Undo2 as Undo2Icon2,
  Unlock as Unlock2,
  Upload as Upload2,
  Usb,
  User as User2,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  UserX,
  Users as Users2,
  UserSquare2,
  Utensils,
  Venus,
  VenusAndMars,
  Vibrate,
  Video as Video2,
  VideoOff,
  Voicemail,
  Volume,
  Volume1,
  Volume2 as Volume22,
  VolumeX as VolumeX2,
  Wallet as Wallet2,
  Wand,
  Wand2,
  Warehouse,
  Watch,
  Wavv,
  Webhook,
  Webcam,
  Youtube,
  Zap as Zap2,
  ZoomIn as ZoomIn2,
  ZoomOut as ZoomOut2,
} from 'lucide-react'

export type IconName = keyof typeof iconMap
